#############################自贸区新增建表语句########################################

CREATE TABLE informix.smp_ftzsendlist (wrkdate CHAR(8) NOT NULL, msgtype CHAR(3) NOT NULL, smpsignno CHAR(20), subdate CHAR(8) NOT NULL, snodeno CHAR(14), sndeq VARCHAR(32) NOT NULL, rnodeno CHAR(14), reveq VARCHAR(32), oldsnodeno CHAR(14), oldwrkdate CHAR(8), oldsndeq VARCHAR(32), oldmsgtype CHAR(3), oldtype CHAR(2), payeropenbkcode CHAR(35), payeracc CHAR(35) NOT NULL, payername VARCHAR(140) NOT NULL, recvopenbkcode CHAR(35), recvacc CHAR(35) NOT NULL, recvname VARCHAR(140) NOT NULL, acctype CHAR(1), transacc CHAR(32), money DECIMAL(15,2) NOT NULL, curtype CHAR(3) NOT NULL, oprttype CHAR(2) NOT NULL, warranttype CHAR(2), warrantdate CHAR(8), warrantno CHAR(20), paypasswd VARCHAR(32), purpose CHAR(1) NOT NULL, appertain VARCHAR(128), inputer VARCHAR(20) NOT NULL, checker CHAR(20), procstate CHAR(2) NOT NULL, inittime DATETIME YEAR TO SECOND, pdtime DATETIME YEAR TO SECOND NOT NULL, setwrkdate CHAR(8), errcode CHAR(4), errdesc VARCHAR(60) NOT NULL, srcflag CHAR(1) NOT NULL, checkstate CHAR(1) NOT NULL, mbcheckstate CHAR(1) NOT NULL, printnum DECIMAL(2,255) NOT NULL, msglenth DECIMAL(8,255) NOT NULL, msgtext TEXT, msgsource CHAR(1) NOT NULL, transtate CHAR(2) NOT NULL, payeropenbkname VARCHAR(140), recvopenbkname VARCHAR(140), fundflow CHAR(4) NOT NULL, sendintermediarycode1 VARCHAR(35), sendintermediaryname1 VARCHAR(140), sendintermediarycode2 VARCHAR(35), sendintermediaryname2 VARCHAR(140), payeraccadd VARCHAR(140), recvintermediarycode1 VARCHAR(35), recvintermediaryname1 VARCHAR(140), recvintermediarycode2 VARCHAR(35), recvintermediaryname2 VARCHAR(140), payeeaccadd VARCHAR(140), costmethod CHAR(3) NOT NULL, sendbnkfee CHAR(15), recvbnkfee CHAR(15), valuesday CHAR(8), trannaturecode CHAR(6), bankremark VARCHAR(210), PRIMARY KEY (subdate, snodeno, sndeq) CONSTRAINT informix.pk_ftz_sendlist);

CREATE TABLE informix.smp_ftzsendlisthis (wrkdate CHAR(8) NOT NULL, msgtype CHAR(3) NOT NULL, smpsignno CHAR(20), subdate CHAR(8) NOT NULL, snodeno CHAR(14), sndeq VARCHAR(32) NOT NULL, rnodeno CHAR(14), reveq VARCHAR(32), oldsnodeno CHAR(14), oldwrkdate CHAR(8), oldsndeq VARCHAR(32), oldmsgtype CHAR(3), oldtype CHAR(2), payeropenbkcode CHAR(35), payeracc CHAR(35) NOT NULL, payername VARCHAR(140) NOT NULL, recvopenbkcode CHAR(35), recvacc CHAR(35) NOT NULL, recvname VARCHAR(140) NOT NULL, acctype CHAR(1), transacc CHAR(32), money DECIMAL(15,2) NOT NULL, curtype CHAR(3) NOT NULL, oprttype CHAR(2) NOT NULL, warranttype CHAR(2), warrantdate CHAR(8), warrantno CHAR(20), paypasswd VARCHAR(32), purpose CHAR(1) NOT NULL, appertain VARCHAR(128), inputer VARCHAR(20) NOT NULL, checker VARCHAR(20), procstate CHAR(2) NOT NULL, inittime DATETIME YEAR TO SECOND, pdtime DATETIME YEAR TO SECOND NOT NULL, setwrkdate CHAR(8), errcode CHAR(4), errdesc VARCHAR(60) NOT NULL, srcflag CHAR(1) NOT NULL, checkstate CHAR(1) NOT NULL, mbcheckstate CHAR(1) NOT NULL, printnum DECIMAL(2,255) NOT NULL, msglenth DECIMAL(8,255) NOT NULL, msgtext TEXT, transmitflag CHAR(1), transtate CHAR(2) NOT NULL, payeropenbkname VARCHAR(140), recvopenbkname VARCHAR(140), fundflow CHAR(4) NOT NULL, sendintermediarycode1 VARCHAR(35), sendintermediaryname1 VARCHAR(140), sendintermediarycode2 VARCHAR(35), sendintermediaryname2 VARCHAR(140), payeraccadd VARCHAR(140), recvintermediarycode1 VARCHAR(35), recvintermediaryname1 VARCHAR(140), recvintermediarycode2 VARCHAR(35), recvintermediaryname2 VARCHAR(140), payeeaccadd VARCHAR(140), costmethod CHAR(3) NOT NULL, sendbnkfee CHAR(15), recvbnkfee CHAR(15), valuesday CHAR(8), trannaturecode CHAR(6), bankremark VARCHAR(210), PRIMARY KEY (subdate, snodeno, sndeq) CONSTRAINT informix.pk_ftz_sendlist_his);

CREATE TABLE informix.smp_ftzrecvlist (wrkdate CHAR(8) NOT NULL, msgtype CHAR(3) NOT NULL, smpsignno CHAR(20), subdate CHAR(8) NOT NULL, snodeno CHAR(14), sndeq VARCHAR(32) NOT NULL, rnodeno CHAR(14), reveq VARCHAR(32), oldsnodeno CHAR(14), oldwrkdate CHAR(8), oldsndeq VARCHAR(32), oldmsgtype CHAR(3), oldtype CHAR(2), payeropenbkcode CHAR(35), payeracc CHAR(35) NOT NULL, payername VARCHAR(140) NOT NULL, recvopenbkcode CHAR(35), recvacc CHAR(35) NOT NULL, recvname VARCHAR(140) NOT NULL, acctype CHAR(1), transacc CHAR(32), money DECIMAL(15,2) NOT NULL, curtype CHAR(3) NOT NULL, oprttype CHAR(2) NOT NULL, warranttype CHAR(2), warrantdate CHAR(8), warrantno CHAR(20), paypasswd VARCHAR(32), purpose CHAR(1) NOT NULL, appertain VARCHAR(128), procstate CHAR(2) NOT NULL, pdtime DATETIME YEAR TO SECOND NOT NULL, setwrkdate CHAR(8), srcflag CHAR(1) NOT NULL, checkstate CHAR(1) NOT NULL, mbcheckstate CHAR(1) NOT NULL, printnum DECIMAL(2,255) NOT NULL, msglenth DECIMAL(8,255) NOT NULL, msgtext TEXT, transmitflag CHAR(1) NOT NULL, transtate CHAR(2) NOT NULL, payeropenbkname VARCHAR(140), recvopenbkname VARCHAR(140), fundflow CHAR(4) NOT NULL, sendintermediarycode1 VARCHAR(35), sendintermediaryname1 VARCHAR(140), sendintermediarycode2 VARCHAR(35), sendintermediaryname2 VARCHAR(140), payeraccadd VARCHAR(140), recvintermediarycode1 VARCHAR(35), recvintermediaryname1 VARCHAR(140), recvintermediarycode2 VARCHAR(35), recvintermediaryname2 VARCHAR(140), payeeaccadd VARCHAR(140), costmethod CHAR(3) NOT NULL, sendbnkfee CHAR(15), recvbnkfee CHAR(15), valuesday CHAR(8), trannaturecode CHAR(6), bankremark VARCHAR(210), PRIMARY KEY (subdate, snodeno, sndeq) CONSTRAINT informix.pk_ftz_recvlist);

CREATE TABLE informix.smp_ftzrecvlisthis (wrkdate CHAR(8) NOT NULL, msgtype CHAR(3) NOT NULL, smpsignno CHAR(20), subdate CHAR(8) NOT NULL, snodeno CHAR(14), sndeq VARCHAR(32) NOT NULL, rnodeno CHAR(14), reveq VARCHAR(32), oldsnodeno CHAR(14), oldwrkdate CHAR(8), oldsndeq VARCHAR(32), oldmsgtype CHAR(3), oldtype CHAR(2), payeropenbkcode CHAR(35), payeracc CHAR(35) NOT NULL, payername VARCHAR(140) NOT NULL, recvopenbkcode CHAR(35), recvacc CHAR(35) NOT NULL, recvname VARCHAR(140) NOT NULL, acctype CHAR(1), transacc CHAR(32), money DECIMAL(15,2) NOT NULL, curtype CHAR(3) NOT NULL, oprttype CHAR(2) NOT NULL, warranttype CHAR(2), warrantdate CHAR(8), warrantno CHAR(20), paypasswd VARCHAR(32), purpose CHAR(1) NOT NULL, appertain VARCHAR(128), procstate CHAR(2) NOT NULL, pdtime DATETIME YEAR TO SECOND NOT NULL, setwrkdate CHAR(8), srcflag CHAR(1) NOT NULL, checkstate CHAR(1) NOT NULL, mbcheckstate CHAR(1) NOT NULL, printnum DECIMAL(2,255) NOT NULL, msglenth DECIMAL(8,255) NOT NULL, msgtext TEXT, transmitflag CHAR(1) NOT NULL, transtate CHAR(2) NOT NULL, payeropenbkname VARCHAR(140), recvopenbkname VARCHAR(140), fundflow CHAR(4) NOT NULL, sendintermediarycode1 VARCHAR(35), sendintermediaryname1 VARCHAR(140), sendintermediarycode2 VARCHAR(35), sendintermediaryname2 VARCHAR(140), payeraccadd VARCHAR(140), recvintermediarycode1 VARCHAR(35), recvintermediaryname1 VARCHAR(140), recvintermediarycode2 VARCHAR(35), recvintermediaryname2 VARCHAR(140), payeeaccadd VARCHAR(140), costmethod CHAR(3) NOT NULL, sendbnkfee CHAR(15), recvbnkfee CHAR(15), valuesday CHAR(8), trannaturecode CHAR(6), bankremark VARCHAR(210), PRIMARY KEY (subdate, snodeno, sndeq) CONSTRAINT informix.pk_ftz_recvlisthis);

CREATE TABLE informix.smp_fundflow (detno VARCHAR(8), fundflow CHAR(4) NOT NULL, smpcode CHAR(3) NOT NULL, PRIMARY KEY (fundflow, smpcode) CONSTRAINT informix.pk_fund_flow);

CREATE TABLE informix.smp2_ftzcappdetail (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), rnodeno VARCHAR(14), batch_id VARCHAR(32), detail_id VARCHAR(8), contract_no VARCHAR(40), organcode VARCHAR(9), feeitem VARCHAR(5), cust_id VARCHAR(32), corpacc_no VARCHAR(35), corpacc_name VARCHAR(60), acc_no VARCHAR(35), acc_name VARCHAR(60), curtype CHAR(3), money DECIMAL(16,2), appertain VARCHAR(60), remark VARCHAR(128), o_entrust_sndeq VARCHAR(32), o_entrust_workdate CHAR(8), o_entrust_snodeno VARCHAR(14), rsflag CHAR(1), msgtype CHAR(3), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), r_sndeq VARCHAR(32), r_workdate CHAR(8), r_state VARCHAR(4), r_desc VARCHAR(60), rcvtime CHAR(14), sndtime CHAR(14), fintime CHAR(14), statebak CHAR(2), checkstate CHAR(2), pdate CHAR(14), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), recvopenbnkcode VARCHAR(14), payopenbnkcode VARCHAR(14), fundflow CHAR(4), PRIMARY KEY (workdate, snodeno, sndeq, rsflag) CONSTRAINT informix.pk_ftzcapp_detail);

CREATE TABLE informix.smp2_ftzcappdetailhis (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), rnodeno VARCHAR(14), batch_id VARCHAR(32), detail_id VARCHAR(8), contract_no VARCHAR(40), organcode VARCHAR(9), feeitem VARCHAR(5), cust_id VARCHAR(32), corpacc_no VARCHAR(35), corpacc_name VARCHAR(60), acc_no VARCHAR(35), acc_name VARCHAR(60), curtype CHAR(3), money DECIMAL(16,2), appertain VARCHAR(60), remark VARCHAR(128), o_entrust_sndeq VARCHAR(32), o_entrust_workdate CHAR(8), o_entrust_snodeno VARCHAR(14), rsflag CHAR(1), msgtype CHAR(3), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), r_sndeq VARCHAR(32), r_workdate CHAR(8), r_state VARCHAR(4), r_desc VARCHAR(60), rcvtime CHAR(14), sndtime CHAR(14), fintime CHAR(14), statebak CHAR(2), checkstate CHAR(2), pdate CHAR(14), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), recvopenbnkcode VARCHAR(14), payopenbnkcode VARCHAR(14), fundflow CHAR(4), PRIMARY KEY (workdate, snodeno, sndeq, rsflag) CONSTRAINT informix.pk_ftzcapp_detailhis);

CREATE TABLE informix.smp2_ftzcappcancel (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), o_sndeq VARCHAR(32), o_workdate CHAR(8), o_snodeno VARCHAR(14), o_msgtype CHAR(3), o_batch_id VARCHAR(32), o_detail_id CHAR(8), money DECIMAL(16,2), msgtype CHAR(3), rsflag CHAR(1), appertain VARCHAR(60), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), pdate CHAR(14), checkstate CHAR(2), statebak CHAR(2), fintime CHAR(14), sndtime CHAR(14), rcvtime CHAR(14), r_desc VARCHAR(60), r_state VARCHAR(4), r_workdate CHAR(8), r_sndeq VARCHAR(32), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), PRIMARY KEY (workdate, snodeno, sndeq, rsflag) CONSTRAINT informix.pk_ftzcapp_cancel);

CREATE TABLE informix.smp2_ftzcappcancelhis (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), o_sndeq VARCHAR(32), o_workdate CHAR(8), o_snodeno VARCHAR(14), o_msgtype CHAR(3), o_batch_id VARCHAR(32), o_detail_id CHAR(8), money DECIMAL(16,2), msgtype CHAR(3), rsflag CHAR(1), appertain VARCHAR(60), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), pdate CHAR(14), checkstate CHAR(2), statebak CHAR(2), fintime CHAR(14), sndtime CHAR(14), rcvtime CHAR(14), r_desc VARCHAR(60), r_state VARCHAR(4), r_workdate CHAR(8), r_sndeq VARCHAR(32), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), PRIMARY KEY (workdate, snodeno, sndeq, rsflag) CONSTRAINT informix.pk_ftzcapp_cancelhis);

CREATE TABLE informix.smp2_cappquerybalance (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno VARCHAR(14) NOT NULL, rnodeno VARCHAR(14) NOT NULL, rsflag CHAR(1) NOT NULL, organcode VARCHAR(9) NOT NULL, feeitem VARCHAR(5) NOT NULL, contract_no VARCHAR(40) NOT NULL, acc_no VARCHAR(35) NOT NULL, acc_name VARCHAR(60) NOT NULL, if_detail INTEGER NOT NULL, detaildate CHAR(16), procstate CHAR(2), r_sndeq VARCHAR(32), r_workdate CHAR(8), r_state VARCHAR(4), r_desc VARCHAR(60), bankquerytime CHAR(14), balance DECIMAL(16,2), balanceusable DECIMAL(16,2), tradenumber INTEGER, sndtime CHAR(14), rcvtime CHAR(14) NOT NULL, PRIMARY KEY (sndeq, workdate, snodeno, rsflag) CONSTRAINT informix.pk_capp_querybalance);

CREATE TABLE informix.smp2_cappquerybalancedetail (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno VARCHAR(14) NOT NULL, tradeno INTEGER NOT NULL, rsflag CHAR(1) NOT NULL, tradetime VARCHAR(14), tradetype VARCHAR(5) NOT NULL, pay_acc_no VARCHAR(35), pay_acc_name VARCHAR(60), get_acc_no VARCHAR(35), get_acc_name VARCHAR(60), money DECIMAL(16,2), remark VARCHAR(128), o_sndeq VARCHAR(32) NOT NULL, o_workdate CHAR(8) NOT NULL, o_snodeno VARCHAR(14) NOT NULL, PRIMARY KEY (sndeq, workdate, snodeno, tradeno, rsflag) CONSTRAINT informix.pk_capp_qbdetail);

CREATE TABLE informix.smp2_cashconsigncontract (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno CHAR(14) NOT NULL, rnodeno CHAR(14) NOT NULL, agreetype CHAR(1) NOT NULL, altermode CHAR(1) NOT NULL, collidtype CHAR(1) NOT NULL, idname VARCHAR(60) NOT NULL, collidno CHAR(20) NOT NULL, collno VARCHAR(35) NOT NULL, collname VARCHAR(60) NOT NULL, feecode CHAR(5) NOT NULL, acctno VARCHAR(35) NOT NULL, acctname VARCHAR(60) NOT NULL, limitmoney DECIMAL(15,2) NOT NULL, appertain VARCHAR(60), pdate CHAR(14), inputer CHAR(10), inputtime CHAR(14), procstate CHAR(2), r_sndeq VARCHAR(32), r_workdate CHAR(8), r_state VARCHAR(4), r_desc VARCHAR(60), PRIMARY KEY (sndeq, workdate, snodeno) CONSTRAINT informix.pk_ftz_cashconsignconstrat);

CREATE TABLE informix.smp2_cashconlist (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno CHAR(14) NOT NULL, rnodeno CHAR(14) NOT NULL, feeitem CHAR(5) NOT NULL, corpacc_no VARCHAR(35) NOT NULL, corpacc_name VARCHAR(60) NOT NULL, acc_no VARCHAR(35) NOT NULL, acc_name VARCHAR(60) NOT NULL, curtype CHAR(3) NOT NULL, money DECIMAL(15,2) NOT NULL, rsflag CHAR(1) NOT NULL, msgtype CHAR(3) NOT NULL, procstate CHAR(2) NOT NULL, transtate CHAR(2), rcvtime VARCHAR(14), sndtime VARCHAR(14), fintime VARCHAR(14), checkstate VARCHAR(2), pdate VARCHAR(14), collidtype CHAR(1) NOT NULL, collidname VARCHAR(60) NOT NULL, collidno CHAR(20) NOT NULL, r_state VARCHAR(4), r_desc VARCHAR(60), r_sndeq VARCHAR(32), r_workdate VARCHAR(8), PRIMARY KEY (sndeq, workdate, rsflag, snodeno) CONSTRAINT informix.pk_ftz_cashconlist);

CREATE TABLE informix.smp2_cashconlisthis (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno CHAR(14) NOT NULL, rnodeno CHAR(14) NOT NULL, feeitem CHAR(5) NOT NULL, corpacc_no VARCHAR(35) NOT NULL, corpacc_name VARCHAR(60) NOT NULL, acc_no VARCHAR(35) NOT NULL, acc_name VARCHAR(60) NOT NULL, curtype CHAR(3) NOT NULL, money DECIMAL(15,2) NOT NULL, rsflag CHAR(1) NOT NULL, msgtype CHAR(3) NOT NULL, procstate CHAR(2) NOT NULL, transtate CHAR(2), rcvtime VARCHAR(14), sndtime VARCHAR(14), fintime VARCHAR(14), checkstate VARCHAR(2), pdate VARCHAR(14), collidtype CHAR(1) NOT NULL, collidname VARCHAR(60) NOT NULL, collidno CHAR(20) NOT NULL, r_state VARCHAR(4), r_desc VARCHAR(60), r_sndeq VARCHAR(32), r_workdate VARCHAR(8), PRIMARY KEY (sndeq, workdate, rsflag, snodeno) CONSTRAINT informix.pk_ftz_cashconlisthis);

CREATE TABLE informix.smp2_cashconflushlist (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno CHAR(14) NOT NULL, rnodeno CHAR(14) NOT NULL, o_sndeq VARCHAR(32) NOT NULL, o_msgtype CHAR(3) NOT NULL, o_workdate VARCHAR(8) NOT NULL, o_snodeno CHAR(14) NOT NULL, money DECIMAL(15,2) NOT NULL, msgtype CHAR(3) NOT NULL, rsflag CHAR(1) NOT NULL, appertain VARCHAR(60), procstate CHAR(2) NOT NULL, transtate CHAR(2), pdate VARCHAR(14), checkstate VARCHAR(2), rcvtime VARCHAR(14), sndtime VARCHAR(14), fintime VARCHAR(14), r_state VARCHAR(4), r_desc VARCHAR(60), r_sndeq VARCHAR(32), r_workdate VARCHAR(8), precollidtype CHAR(1) NOT NULL, preidname VARCHAR(60) NOT NULL, precollidno CHAR(20) NOT NULL, precollno VARCHAR(35) NOT NULL, precollname VARCHAR(60) NOT NULL, prefeecode CHAR(5) NOT NULL, preacctno VARCHAR(35) NOT NULL, preacctname VARCHAR(60) NOT NULL, currencysymbol CHAR(3) NOT NULL, PRIMARY KEY (sndeq, workdate, rsflag, snodeno) CONSTRAINT informix.pk_cash_conflushlist);

CREATE TABLE informix.smp2_cashconbalance (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno CHAR(14) NOT NULL, rnodeno CHAR(14) NOT NULL, rsflag CHAR(1) NOT NULL, feeitem CHAR(5) NOT NULL, acc_no VARCHAR(35) NOT NULL, acc_name VARCHAR(60) NOT NULL, if_detail CHAR(1) NOT NULL, detaildate CHAR(16), procstate CHAR(2) NOT NULL, rcvtime VARCHAR(14), sndtime VARCHAR(14), collidtype CHAR(1) NOT NULL, collidno CHAR(20) NOT NULL, collno VARCHAR(35) NOT NULL, collname VARCHAR(60) NOT NULL, r_sndeq VARCHAR(32), r_workdate CHAR(8), r_state CHAR(4), remark VARCHAR(60), bankquerytime VARCHAR(14), balance CHAR(15), balanceusable CHAR(15), tradenumber CHAR(8), PRIMARY KEY (sndeq, workdate, rsflag, snodeno) CONSTRAINT informix.pk_ftz_cashconbalance);

CREATE TABLE informix.smp2_cashconbalancedetail (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno VARCHAR(14) NOT NULL, tradeno INTEGER NOT NULL, rsflag CHAR(1) NOT NULL, tradetime VARCHAR(14), tradetype VARCHAR(5) NOT NULL, pay_acc_no VARCHAR(35), pay_acc_name VARCHAR(60), get_acc_no VARCHAR(35), get_acc_name VARCHAR(60), money DECIMAL(16,2), remark VARCHAR(128), o_sndeq VARCHAR(32) NOT NULL, o_workdate CHAR(8) NOT NULL, o_snodeno VARCHAR(14) NOT NULL, PRIMARY KEY (sndeq, workdate, snodeno, tradeno, rsflag) CONSTRAINT informix.pk_cashcon_qbdetail);


CREATE TABLE informix.smp2_plpdetail (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), rnodeno VARCHAR(14), batch_id VARCHAR(32), detail_id VARCHAR(8), collidtype CHAR(1), collidno VARCHAR(20), feeitem VARCHAR(5), payeracc_no VARCHAR(35), payeracc_name VARCHAR(60), payeeacc_no VARCHAR(35), payeeacc_name VARCHAR(60), curtype CHAR(3), money DECIMAL(16,2), appertain VARCHAR(60), remark VARCHAR(128), o_entrust_sndeq VARCHAR(32), o_entrust_workdate CHAR(8), o_entrust_snodeno VARCHAR(14), rsflag CHAR(1), msgtype CHAR(3), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), r_sndeq VARCHAR(32), r_workdate CHAR(8), r_state VARCHAR(4), r_desc VARCHAR(60), rcvtime CHAR(14), sndtime CHAR(14), fintime CHAR(14), statebak CHAR(2), checkstate CHAR(2), pdate CHAR(14), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), recvopenbnkcode VARCHAR(14), payopenbnkcode VARCHAR(14), payermoneybank VARCHAR(14), payeemoneybank VARCHAR(14), fundflow CHAR(4), PRIMARY KEY (sndeq, workdate, snodeno, rsflag) CONSTRAINT informix.pk_plp_detail);

CREATE TABLE informix.smp2_plpdetailhis (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), rnodeno VARCHAR(14), batch_id VARCHAR(32), detail_id VARCHAR(8), collidtype CHAR(1), collidno VARCHAR(20), feeitem VARCHAR(5), payeracc_no VARCHAR(35), payeracc_name VARCHAR(60), payeeacc_no VARCHAR(35), payeeacc_name VARCHAR(60), curtype CHAR(3), money DECIMAL(16,2), appertain VARCHAR(60), remark VARCHAR(128), o_entrust_sndeq VARCHAR(32), o_entrust_workdate CHAR(8), o_entrust_snodeno VARCHAR(14), rsflag CHAR(1), msgtype CHAR(3), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), r_sndeq VARCHAR(32), r_workdate CHAR(8), r_state VARCHAR(4), r_desc VARCHAR(60), rcvtime CHAR(14), sndtime CHAR(14), fintime CHAR(14), statebak CHAR(2), checkstate CHAR(2), pdate CHAR(14), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), recvopenbnkcode VARCHAR(14), payopenbnkcode VARCHAR(14), payermoneybank VARCHAR(14), payeemoneybank VARCHAR(14), fundflow CHAR(4), PRIMARY KEY (sndeq, workdate, snodeno, rsflag) CONSTRAINT informix.pk_plp_detailhis);

CREATE TABLE informix.smp2_plpbatch (batch_id VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno VARCHAR(14) NOT NULL, forepartno VARCHAR(32), forepartdate CHAR(8), msgtype CHAR(3) NOT NULL, payermoneybank VARCHAR(14), curtype CHAR(3) NOT NULL, sum_cnt INTEGER NOT NULL, sum_amout DECIMAL(16,2) NOT NULL, transtate CHAR(2) DEFAULT '00' NOT NULL, procstate CHAR(2) NOT NULL, transtatedesc VARCHAR(60), r_success_cnt INTEGER, r_success_amout DECIMAL(16,2), r_sndeq VARCHAR(32), r_workdate CHAR(8), rcvtime CHAR(14) NOT NULL, sndtime CHAR(14), fintime CHAR(14), checkstate CHAR(2), pdate CHAR(14), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), PRIMARY KEY (batch_id, workdate, snodeno) CONSTRAINT informix.pk_plp_batch);

CREATE TABLE informix.smp2_plpbatchhis (batch_id VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno VARCHAR(14) NOT NULL, forepartno VARCHAR(32), forepartdate CHAR(8), msgtype CHAR(3) NOT NULL, payermoneybank VARCHAR(14), curtype CHAR(3) NOT NULL, sum_cnt INTEGER NOT NULL, sum_amout DECIMAL(16,2) NOT NULL, transtate CHAR(2) DEFAULT '00' NOT NULL, procstate CHAR(2) NOT NULL, transtatedesc VARCHAR(60), r_success_cnt INTEGER, r_success_amout DECIMAL(16,2), r_sndeq VARCHAR(32), r_workdate CHAR(8), rcvtime CHAR(14) NOT NULL, sndtime CHAR(14), fintime CHAR(14), checkstate CHAR(2), pdate CHAR(14), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), PRIMARY KEY (batch_id, workdate, snodeno) CONSTRAINT informix.pk_plp_batchhis);

CREATE TABLE informix.smp2_plpcancel (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), o_sndeq VARCHAR(32), o_workdate CHAR(8), o_snodeno VARCHAR(14), o_msgtype CHAR(3), o_batch_id VARCHAR(32), o_detail_id CHAR(8), money DECIMAL(16,2), msgtype CHAR(3), rsflag CHAR(1), appertain VARCHAR(60), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), pdate CHAR(14), checkstate CHAR(2), statebak CHAR(2), fintime CHAR(14), sndtime CHAR(14), rcvtime CHAR(14), r_desc VARCHAR(60), r_state VARCHAR(4), r_workdate CHAR(8), r_sndeq VARCHAR(32), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), PRIMARY KEY (sndeq, workdate, snodeno, rsflag) CONSTRAINT informix.pk_plp_cancel);

CREATE TABLE informix.smp2_plpcancelhis (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), o_sndeq VARCHAR(32), o_workdate CHAR(8), o_snodeno VARCHAR(14), o_msgtype CHAR(3), o_batch_id VARCHAR(32), o_detail_id CHAR(8), money DECIMAL(16,2), msgtype CHAR(3), rsflag CHAR(1), appertain VARCHAR(60), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), pdate CHAR(14), checkstate CHAR(2), statebak CHAR(2), fintime CHAR(14), sndtime CHAR(14), rcvtime CHAR(14), r_desc VARCHAR(60), r_state VARCHAR(4), r_workdate CHAR(8), r_sndeq VARCHAR(32), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), PRIMARY KEY (sndeq, workdate, snodeno, rsflag) CONSTRAINT informix.pk_plp_cancelhis);

CREATE TABLE informix.smp2_plpfundsettle (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), forepartno VARCHAR(32), forepartdate CHAR(8), rnodeno VARCHAR(14), o_entrust_snodeno VARCHAR(14), o_entrust_rnodeno VARCHAR(14), o_entrust_sndeq VARCHAR(32), o_entrust_smpcode CHAR(3), payernodeno VARCHAR(14), payeenodeno VARCHAR(14), financetype CHAR(1), payeracc_no VARCHAR(35), payeeacc_name VARCHAR(60), payeeacc_no VARCHAR(35), payeracc_name VARCHAR(60), curtype CHAR(3), money DECIMAL(16,2), appertain VARCHAR(60), remark VARCHAR(128), rsflag CHAR(1), msgtype CHAR(3), procstate CHAR(2), transtate CHAR(2), transtatedesc VARCHAR(60), r_sndeq VARCHAR(32), r_workdate CHAR(8), r_state VARCHAR(4), r_desc VARCHAR(60), rcvtime CHAR(14), sndtime CHAR(14), fintime CHAR(14), statebak CHAR(2), checkstate CHAR(2), pdate CHAR(14), inputer CHAR(10), inputtime CHAR(14), checker CHAR(10), checktime CHAR(14), PRIMARY KEY (sndeq, workdate, snodeno, rsflag) CONSTRAINT informix.pk_plp_fundsettle);

CREATE TABLE informix.smp2_plpfundsettledetail (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), rnodeno VARCHAR(14), rsflag CHAR(1), tradetime CHAR(8), o_fundseteq VARCHAR(32), o_smpcode CHAR(3), o_sndeq VARCHAR(32), o_workdate VARCHAR(8), o_snodeno VARCHAR(14), r_code VARCHAR(4), remark VARCHAR(60), PRIMARY KEY (sndeq, workdate, snodeno, rsflag) CONSTRAINT informix.pk_plp_fundsettledetail);

CREATE TABLE informix.smp2_plpfundsetacctregist (sndeq VARCHAR(32), workdate CHAR(8), snodeno VARCHAR(14), rnodeno VARCHAR(14), rsflag CHAR(1), custodiancode VARCHAR(14), corpname VARCHAR(60), organcode VARCHAR(9), custodianacct VARCHAR(35), acctname VARCHAR(60), changemode CHAR(1), defaultsetacctflag CHAR(1), procstate CHAR(2), remark VARCHAR(60), limitmoney DECIMAL(16,2), rcvtime CHAR(14), sndtime CHAR(14), PRIMARY KEY (workdate, snodeno, sndeq, rsflag) CONSTRAINT informix.pk_plp_fundsetacctregist);

CREATE TABLE informix.smp2_plpquerybalance (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno CHAR(14) NOT NULL, rnodeno CHAR(14) NOT NULL, rsflag CHAR(1) NOT NULL, feeitem CHAR(5) NOT NULL, acc_no VARCHAR(35) NOT NULL, acc_name VARCHAR(60) NOT NULL, if_detail CHAR(1) NOT NULL, detaildate CHAR(16) NOT NULL, procstate CHAR(2) NOT NULL, rcvtime DATETIME YEAR TO SECOND NOT NULL, sndtime DATETIME YEAR TO SECOND NOT NULL, collidtype CHAR(1) NOT NULL, collidno CHAR(20) NOT NULL, collno VARCHAR(35) NOT NULL, collname VARCHAR(60) NOT NULL, r_sndeq VARCHAR(32) NOT NULL, r_workdate CHAR(8) NOT NULL, r_state CHAR(4) NOT NULL, remark VARCHAR(60), bankquerytime DATETIME YEAR TO SECOND NOT NULL, balance CHAR(15), balanceusable CHAR(15), tradenumber CHAR(8), PRIMARY KEY (sndeq, workdate, rsflag, snodeno) CONSTRAINT informix.pk_plp_querybalance);

CREATE TABLE informix.smp2_plpquerybalancedetail (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno CHAR(14) NOT NULL, o_sndeq VARCHAR(32) NOT NULL, o_workdate CHAR(8) NOT NULL, o_snodeno CHAR(14) NOT NULL, tradeno CHAR(8) NOT NULL, tradetype CHAR(5) NOT NULL, tradetime CHAR(14) NOT NULL, pay_acc_no VARCHAR(35) NOT NULL, pay_acc_name VARCHAR(60) NOT NULL, get_acc_no VARCHAR(35) NOT NULL, get_acc_name VARCHAR(60) NOT NULL, money DECIMAL(15,2) NOT NULL, remark VARCHAR(128) NOT NULL, PRIMARY KEY (sndeq, workdate, snodeno) CONSTRAINT informix.pk_plp_querybalancedetail);

CREATE TABLE informix.smp2_plpgroupcheck (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, msgtype CHAR(3) NOT NULL, checkworkdate CHAR(8) NOT NULL, rnodeno VARCHAR(14) NOT NULL, curtype CHAR(3) NOT NULL, crtotalnum INTEGER NOT NULL, crtotalamt DECIMAL(16,2) NOT NULL, detotalnum INTEGER NOT NULL, detotalamt DECIMAL(16,2) NOT NULL, rcvtime VARCHAR(14) NOT NULL, checkstate CHAR(2), PRIMARY KEY (msgtype, checkworkdate, rnodeno) CONSTRAINT informix.pk_plp_groupcheck);

CREATE TABLE informix.smp2_plpgroupnetting (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, checkworkdate CHAR(8) NOT NULL, rnodeno VARCHAR(14) NOT NULL, curtype CHAR(3) NOT NULL, crtotalnum INTEGER NOT NULL, crtotalamt DECIMAL(16,2) NOT NULL, detotalnum INTEGER NOT NULL, detotalamt DECIMAL(16,2) NOT NULL, cdflag CHAR(1) NOT NULL, balanceamt DECIMAL(16,2) NOT NULL, checkcnt INTEGER NOT NULL, rcvtime VARCHAR(14) NOT NULL, checkstate CHAR(2), PRIMARY KEY (checkworkdate, rnodeno) CONSTRAINT informix.pk_plp_groupnetting);

CREATE TABLE informix.smp2_plpitemcheck (serialno VARCHAR(8) DEFAULT '00000000' NOT NULL, cendate CHAR(8) NOT NULL, cenflow VARCHAR(32) NOT NULL, smpcode CHAR(3) NOT NULL, sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno VARCHAR(14) NOT NULL, rnodeno VARCHAR(14) NOT NULL, money DECIMAL(16,2) NOT NULL, checkstate CHAR(2), redostate CHAR(2) DEFAULT '00' NOT NULL, PRIMARY KEY (sndeq, workdate, snodeno, serialno) CONSTRAINT informix.pk_plp_itemcheck);

CREATE TABLE informix.smp2_fundgroupcheck (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, msgtype CHAR(3) NOT NULL, checkworkdate CHAR(8) NOT NULL, rnodeno VARCHAR(14) NOT NULL, curtype CHAR(3) NOT NULL, crtotalnum INTEGER NOT NULL, crtotalamt DECIMAL(16,2) NOT NULL, detotalnum INTEGER NOT NULL, detotalamt DECIMAL(16,2) NOT NULL, rcvtime VARCHAR(14) NOT NULL, checkstate CHAR(2), PRIMARY KEY (msgtype, checkworkdate, rnodeno) CONSTRAINT informix.pk_fund_groupcheck);

CREATE TABLE informix.smp2_fundgroupnetting (sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, checkworkdate CHAR(8) NOT NULL, rnodeno VARCHAR(14) NOT NULL, curtype CHAR(3) NOT NULL, crtotalnum INTEGER NOT NULL, crtotalamt DECIMAL(16,2) NOT NULL, detotalnum INTEGER NOT NULL, detotalamt DECIMAL(16,2) NOT NULL, cdflag CHAR(1) NOT NULL, balanceamt DECIMAL(16,2) NOT NULL, checkcnt INTEGER NOT NULL, rcvtime VARCHAR(14) NOT NULL, checkstate CHAR(2), PRIMARY KEY (checkworkdate, rnodeno) CONSTRAINT informix.pk_fund_groupnetting);

CREATE TABLE informix.smp2_funditemcheck (serialno VARCHAR(8) DEFAULT '00000000' NOT NULL, cendate CHAR(8) NOT NULL, cenflow VARCHAR(32) NOT NULL, smpcode CHAR(3) NOT NULL, sndeq VARCHAR(32) NOT NULL, workdate CHAR(8) NOT NULL, snodeno VARCHAR(14) NOT NULL, rnodeno VARCHAR(14) NOT NULL, money DECIMAL(16,2) NOT NULL, checkstate CHAR(2), redostate CHAR(2) DEFAULT '00' NOT NULL, PRIMARY KEY (sndeq, workdate, snodeno, serialno) CONSTRAINT informix.pk_fund_itemcheck);

CREATE TABLE informix.smp2_plpfundbalance (workdate CHAR(8) NOT NULL, rnodeno CHAR(14), liqudate CHAR(8) NOT NULL, liquseq CHAR(2) NOT NULL, creditnum INTEGER NOT NULL, creditamount DECIMAL(15,2) NOT NULL, debitnum INTEGER NOT NULL, debitamount DECIMAL(15,2) NOT NULL, creditallnum VARCHAR(8), creditallamount DECIMAL(15,2) NOT NULL, debitallnum VARCHAR(8), debitallamount DECIMAL(15,2) NOT NULL, flag1 CHAR(1), allmoney DECIMAL(15,2) NOT NULL, balanceacct VARCHAR(35), balancebank VARCHAR(14), flag2 CHAR(1), money DECIMAL(15,2) NOT NULL, PRIMARY KEY (workdate, rnodeno, liqudate, liquseq));

CREATE TABLE informix.smp2_skipdayinterest (workdate CHAR(8) NOT NULL, rnodeno CHAR(14), liqudate CHAR(8) NOT NULL, liquseq CHAR(2) NOT NULL, creditnum INTEGER NOT NULL, creditamount DECIMAL(15,2) NOT NULL, debitnum INTEGER NOT NULL, debitamount DECIMAL(15,2) NOT NULL, currencytype VARCHAR(3), flag CHAR(1), allinterest DECIMAL(15,2) NOT NULL, balancedate CHAR(8) NOT NULL, busitype VARCHAR(3), moneyrate VARCHAR(8), interest DECIMAL(15,2) NOT NULL);
